### ISSUE TITLE
str' object has no attribute 'get_svg_classes'

### ISSUE THREAD

**Issue by poojabeniwal** [heitzmann/gdspy#202] opened 2022-01-12 07:55 UTC
I am trying to convert gds file into svg file.
But facing error "str' object has no attribute 'get_svg_classes' ".
I was not able to understand how to resolve this issue, it would be great if you could help me to resolve this issue.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/90715632/149085747-dd3590d0-86f3-4439-96fe-00e10cc2418c.png">

import gdspy
import numpy
import sys
import copy

import os 
os.environ['path'] += r';C:\Program Files\UniConvertor-2.0rc5\dlls'
import cairosvg

layout= gdspy.GdsLibrary(infile='C:\\Users\\pooja\\Downloads\\p1.gds')
cellList = layout.cells
cellList
for val in cellList:
        cell = cellList[val]
        cell.remove_paths(lambda path: path.layers[0] != val)
        cell.remove_labels(lambda label: label.layer != val)
        print(f"Processing {cell}")
        cell.write_svg('C:\\Users\\pooja\\svg\\AA_project_layout.svg')

**Comment by heitzmann** [comment] 2022-01-13 11:07
Thanks for the report. I've pushed a fix in the latest commit. Can you check if it works for you, @poojabeniwal?

**Comment by poojabeniwal** [comment] 2022-01-13 12:47
Thank you for your response.
Now I am getting another error.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/90715632/149332837-7364d261-3e53-480c-829d-5c4ce32750e2.png">

**Comment by heitzmann** [comment] 2022-01-13 13:14
This error looks strange, because `ref` is assigned on the previous line. Can you share the GDSII file and the script that reproduces the error so that I can investigate the problem?

**Comment by poojabeniwal** [comment] 2022-01-13 13:59
When there are no references in gds (train.gds and test.gds) it works fine
But when there are references in gds (all other gds) it's throwing an error.

I have attached the script and the all gds.



[gds_to_svg.zip](https://github.com/heitzmann/gdspy/files/7863244/gds_to_svg.zip)

**Comment by heitzmann** [comment] 2022-01-13 14:47
The files you sent are working fine. Have you restarted your notebook kernel after reinstalling gdspy?

**Comment by poojabeniwal** [comment] 2022-01-13 16:24
Thank you, It's working now. I really appreciate your help.

**Closed** 2022-01-13 16:55 UTC
